CadAluno/Models/Aluno.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CadAluno.Models
{
    public class Aluno
    {
        public int Id {get; set;}
        public string Nome {get; set;}
        public int Idade {get; set;}
    }
}

CadAluno/Models/CadAlunoContext.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CadAluno.Models;

public partial class CadAlunoContext : DbContext
{
    public CadAlunoContext()
    {
    }

    public CadAlunoContext(DbContextOptions<CadAlunoContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Frutum> Fruta { get; set; }
    public virtual DbSet<Aluno> Alunos { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Server=NOTE13-S21\\SQLEXPRESS;Database=CadAluno;User Id=sa;Password=senai@134;TrustServerCertificate=True;");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Frutum>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__fruta__3213E83F33F8F091");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

CadAluno/Models/ErrorViewModel.cs
namespace CadAluno.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

CadAluno/Models/Fruta.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CadAluno.Models
{
    public class Fruta
    {
        //id
        //Nome
        //Cor

        public int Id;
        public string Nome = "";
        public string Cor= "";
        public string Categoria= "";
    }
}

CadAluno/Models/Frutum.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CadAluno.Models;

[Table("fruta")]
public partial class Frutum
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Nome { get; set; } = null!;

    [StringLength(255)]
    [Unicode(false)]
    public string Cor { get; set; } = null!;

    [StringLength(255)]
    [Unicode(false)]
    public string Categoria { get; set; } = null!;
}

CadAluno/Controllers/AlunosController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using CadAluno.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CadAluno.Controllers
{

    public class AlunosController : Controller
    {
        private readonly ILogger<AlunosController> _logger;

        public AlunosController(ILogger<AlunosController> logger)
        {
            _logger = logger;
        }

        // private static List<Aluno> aluno = new List<Aluno>
        // {
        //     new Aluno{ Id= 1, Nome = "Felipe", Idade = 17,},
        //     new Aluno{Id = 2, Nome = "Lucas", Idade = 16,},
        //     new Aluno{Id = 3, Nome = "Thiago", Idade = 17,},
        //     new Aluno{Id = 4, Nome = "Crevelaro", Idade = 17,}
        // };

        private readonly CadAlunoContext _context;

        private readonly ILogger<AlunosController> logger;

        public AlunosController (ILogger<AlunosController> logger, CadAlunoContext context)
        {
           _logger = logger;
           _context = context;
        }

        // public IActionResult Index()
        // {
        //     return View(aluno);
        // }

        public async Task<IActionResult> Create(Aluno aluno)
        {
           _context.Add(aluno);
           await _context.SaveChangesAsync();

           return RedirectToAction(nameof(Index));
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        // public IActionResult Create(Aluno alunos)
        // {
        //     //salvar no arreay
        //     alunos.Id = aluno.Max(a => a.Id) + 1; //cira o próximo id
        //     aluno.Add(alunos);
        //     //redireciaonar o usuário para a Indez
        //     return RedirectToAction("Index");
        // }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

CadAluno/Controllers/FrutasController.cs
using CadAluno.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CadAluno.Controllers
{
    public class FrutasController : Controller
    {
        private readonly ILogger<FrutasController> _logger;
        private readonly CadAlunoContext _context;

        public FrutasController(ILogger<FrutasController> logger, CadAlunoContext context)
        {
            _logger = logger;
            _context = context;
        }

        //Criar uma lista de Frutas
        // private static List<Fruta> fruta = new List<Fruta>
        // {
        //     new Fruta{Id = 1, Nome = "Maçã" , Cor = "Vermelha", Categoria = "Tropical"},
        //     new Fruta{Id = 2, Nome = "Banana" , Cor = "Amarela", Categoria = "Tropical"},
        //     new Fruta{Id = 3, Nome = "Laranja" , Cor = "Laranja", Categoria = "Cítrica"},
        //     new Fruta{Id = 4, Nome = "Abacaxi" , Cor = "Amarelo", Categoria = "Cítrica"}
        // };

        public async Task<IActionResult> Index()
        {
            var frutas = await _context.Fruta.ToListAsync();
            return View(frutas);
        }

        public IActionResult Create()
        {
            return View();
        }

        //Método para salvar uma fruta 
        [HttpGet]
        // // public IActionResult Cerate(Fruta frutas)
        // // {
        // //     //Salvar no array 
        // //     frutas.Id = fruta.Max(f => f.Id) + 1;
        // //     fruta.Add(frutas);
        // //     //Redirecionar o usuário para o Index
        //     return RedirectToAction("Index");
        // }
        
        public IActionResult Citricas()
        {
            return View();
        }
        public IActionResult Tropicais()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

CadAluno/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using CadAluno.Models;

namespace CadAluno.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    public IActionResult QuemSomos()
    {
        return View();
    }


    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

CadAluno/Views/Alunos/Create.cshtml
@model CadAluno.Models.Aluno
<h1>Cadastro de Aluno</h1>

<form asp-action="Create" method="post">
    <label for="">Nome</label>
    <input asp-for="Nome" class="form-control">
    <br>

    <label for="">Idade</label>
    <input asp-for="Idade" class="form-control">
    <br>
    
    <label for="">Id</label>
    <input asp-for="Id" class="form-control">

    <br>
    <br>
    <button class="btn btn-success">Salvar</button>
</form>

CadAluno/Views/Alunos/Index.cshtml
@model List<CadAluno.Models.Aluno>

<h1>Página de Alunos</h1>

<h2>Lista de Alunos</h2>

@foreach (var Aluno in Model)
{
    <p>
        Id: @Aluno.Id <br>
        Nome: @Aluno.Nome <br>
        Idade: @Aluno.Idade <br>

    </p>
}

CadAluno/Views/Frutas/Citricas.cshtml
<h1>Página de Frutas Cítricas</h1>

CadAluno/Views/Frutas/Create.cshtml
@model CadAluno.Models.Fruta

<h1>Cadastre de Fruta</h1>

@*Criar o Fomulário de cadastro de fruta*@
<form asp-action="Create" method= "post">
<label for="">Nome:</label> 
<input asp-for="Nome" class="from-control">

<br>
<label>Cor:</label>
<input asp-for="Cor" class="from-control">

<br>
<label>Categoria:</label>
<input asp-for="Categoria" class="from-control">

<br>
<br>
<button class="btn btn-success">Salvar</button>
</form>

CadAluno/Views/Frutas/Tropicais.cshtml
<h1>Páginas de Frutas Tropicais</h1>

CadAluno/Views/Frutas/index.cshtml
@model List<CadAluno.Models.Frutum>

<h1>Página de Frutas</h1>

<h2>Lista de Frutas</h2>

@foreach(var fruta in Model){
  <p>
    id: @fruta.Id <br>
    Nome: @fruta.Nome <br>
    Cor: @fruta.Cor <br>
    Categoria: @fruta.Categoria <br>
  </p>

}

CadAluno/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Primeiro App";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CadAluno/Views/Home/QuemSomos.cshtml
<h1>Página Quem Somos</h1> 

<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sapiente, quaerat, facilis harum placeat maxime repellendus quidem nesciunt quos assumenda, ab itaque cumque quas? Repellat soluta voluptatibus saepe officia ipsum quisquam!</p>

<a  asp-controller="Home" asp-action="Index">Voltar pra Home</a>

CadAluno/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CadAluno</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CadAluno.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CadAluno</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="QuemSomos">QuemSomos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
       <div class="container">
       
                 <a asp-controller="Alunos" asp-action="Index">Lista de Alunos </a>
                 <a asp-controller="Alunos" asp-action="Create">Cadastrar Alunos </a>
                 <a asp-controller="Frutas" asp-action="Index"> Lista Frutas</a>
                 <a asp-controller="Frutas" asp-action="Create"> Cadastrar Frutas</a>
                 <a asp-controller="Frutas" asp-action="Citricas"> Frutas Cítricas</a>
                 <a asp-controller="Frutas" asp-action="Tropicais"> Frutas Tropicais</a>
             
         
      </div>

          <div class="container">
            &copy; 2025 - CadAluno - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>