DevConnect/Controllers/FeedController.cs
using DevConnect.Models;
using Microsoft.AspNetCore.Mvc;
using DevConnect.Contexts;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using System.Linq.Expressions;


namespace MvcDevConnect.Controllers
{
    public class FeedController : Controller
    {

        private readonly DevConnectContext _context;
        private readonly ILogger<FeedController> _logger;

        public FeedController(ILogger<FeedController> logger, DevConnectContext context)
        {
            _logger = logger;
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            try
            {
                List<TbPublicacao> publicacaos = await _context.TbPublicacao
                .Include(p => p.IdUsuarioNavigation)
                .ToListAsync();
                return View(publicacaos);
            }
            catch
            {
                throw;
            }
        }

        [HttpPost]
        public async Task<IActionResult> Index(IFormCollection form)
        {
            // Console.WriteLine($"{form["NomeCompleto"]}");
            // Console.WriteLine($"{form.Files[0].FileName}");

            TbPublicacao novaPostagem = new TbPublicacao
            {
                Descricao = form["Descricao"].ToString(),
                ImagemUrl = form["ImagemUrl"].ToString(),
                DataPublicacao = DateOnly.FromDateTime(DateTime.Now)
            };

            if (form.Files.Count > 0)
            {
                var file = form.Files[0];
                var folder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images");


                if (!Directory.Exists(folder))
                {
                    Directory.CreateDirectory(folder);
                }

                var path = Path.Combine(folder, file.FileName);

                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }
                ;

                novaPostagem.ImagemUrl = file.FileName;

            }

            try
            {
                _context.TbPublicacao.Add(novaPostagem);

                await _context.SaveChangesAsync();
                List<TbPublicacao> publicacaos = await _context.TbPublicacao.ToListAsync();
                ViewBag.PublicacaoCadastrada = "Cadastrada";
                return View(publicacaos);

            }
            catch (System.Exception)
            {
                throw;
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

DevConnect/Controllers/UsuarioController.cs
using System.Threading.Tasks;
using DevConnect.Contexts;
using DevConnect.Models;
using Microsoft.AspNetCore.Mvc;


namespace DevConnect.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly DevConnectContext _context;
        private readonly ILogger<UsuarioController> _logger;

        public UsuarioController(ILogger<UsuarioController> logger, DevConnectContext context)
        {
            _logger = logger;
            _context = context;
        }

       [HttpGet]
        public IActionResult Index()
        {
             ViewBag.UsuarioNovoCadastrado = "";
              TempData["UsuarioNovoCadastrado"] = "";
            return View();
        }

        [HttpPost]

        public async Task<IActionResult> Index(IFormCollection form)
        {

            // Console.WriteLine($"{form["NomeCompleto"]}");
            // Console.WriteLine($"{form.Files[0].FileName}");

            TbUsuario novoUsuario = new TbUsuario
            {
                NomeCompleto = form["NomeCompleto"].ToString(),
                NomeDeUsuario = form["NomeDeUsuario"].ToString(),
                Email = form["Email"].ToString(),
                Senha = form["Senha"].ToString()
            };

            if (form.Files.Count > 0)
            {
                var file = form.Files[0];
                var folder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images");

                if (!Directory.Exists(folder))
                {
                    Directory.CreateDirectory(folder);
                }

                var path = Path.Combine(folder, file.FileName);

                using(var stream = new FileStream(path, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }

                novoUsuario.FotoPerfilUrl = file.FileName;
            }

              else
                {
                novoUsuario.FotoPerfilUrl = "";
                }

                try
                {
                    _context.TbUsuario.Add(novoUsuario);


                   await _context.SaveChangesAsync();
                    ViewBag.UsuarioNovoCadastrado = "";
                    TempData["UsuarioNovoCadastrado"] = "Cadastrado";

                    return RedirectToAction("Index", "Home");
                }
                catch (System.Exception)
                {
                    ViewBag.UsuarioNovoCadastrado = "Nao cadastrato";
                    TempData["UsuarioNovoCadastrado"] = "";
                //Vamos pedir para a view falar ao usuário que não foi cadastro
                 return View();

                }
            
        }
        public IActionResult Perfil()
        {
            return View();
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

DevConnect/Views/Feed/Index.cshtml
@using Microsoft.IdentityModel.Tokens
@model List<DevConnect.Models.TbPublicacao>
 <h1>Página de Feed</h1>

<link rel="stylesheet" href="~/css/feed.css">

<script defer>
    let PublicacaoNovaCadastrado = "@ViewBag.PublicacaoCadastrada";

    if(PublicacaoNovaCadastrado == "Nao cadastrada"){
      alert("Usuário não cadastrado! Tente novamente!!!");
    }

    else if(PublicacaoNovaCadastrado == "Cadastrada"){
      alert("Publicação postada...");
    }

</script>

 <h1>Tela Feed - DevConnect</h1>

  <header id="cabecalho">

    <nav>
      <a id="logo-desktop" asp-controller="Home" asp-action="Index">
        <img src="../images/logo-devconnect-md.svg" alt="Logo da empressa DevConnect">
      </a>

      <a id="logo-mobile" href="./feed.html">
        <img src="../images/logo-devconnect-sm.svg" alt="Logo da empressa DevConnect">
      </a>

      <div class="cabecalho-acoes">

        <a asp-controller="Home" asp-action="Index">
          <img src="../images/icone-casa-azul.svg" alt="Ícone de uma casa na cor azul">
        </a>

        <a href="#">
          <img src="../images/icone-coracao-azul.svg" alt="Ícone de uma coração azul">
        </a>

        <a asp-controller="Usuario" asp-action="Perfil">
          <img class="foto-perfil" src="../images/bill-it-acoisa.jpg" alt="Foto de perfil">
        </a>

      </div>
    </nav>
  </header>

  <main>
    <div class="container-flex-publi">

      <section id="storys" class="formulario">
        <article class="card-story">
          <a href="#">
            <img src="../images/bill-it-acoisa.jpg" alt="Foto de perfil">
            <span>pennywise</span>
          </a>
        </article>

        <article class="card-story">
          <a href="#">
            <img src="../images/bill-it-acoisa.jpg" alt="Foto de perfil">
            <span>pennywise</span>
          </a>
        </article>

        <article class="card-story">
          <a href="#">
            <img src="../images/bill-it-acoisa.jpg" alt="Foto de perfil">
            <span>pennywise</span>
          </a>
        </article>

        <article class="card-story">
          <a href="#">
            <img src="../images/bill-it-acoisa.jpg" alt="Foto de perfil">
            <span>pennywise</span>
          </a>
        </article>
        
        <article class="card-story">
          <a href="#">
            <img src="../images/bill-it-acoisa.jpg" alt="Foto de perfil">
            <span>pennywise</span>
          </a>
        </article>
        
        <article class="card-story">
          <a href="#">
            <img src="../images/bill-it-acoisa.jpg" alt="Foto de perfil">
            <span>pennywise</span>
          </a>
        </article>


        <article class="card-story">
          <a href="#">
            <img src="../images/98629953578bf8905079d4a2dfcc407f.jpg" alt="Foto de perfil"> <span>chavito</span>
          </a>
        </article>

        <article class="card-story">
          <a href="#">
            <img src="../images/d5c40eee39a0cec1e4b56499e4eef910.jpg" alt="Foto de perfil"> <span>bantata</span>
          </a>
        </article>

        <article class="card-story">
          <a href="#">
            <img src="../images/images.jpg" alt="Foto de perfil"> <span>rogeriio</span>
          </a>

        </article>
      </section>

      <section id="cadastro-publi" class="estilo-formulario">

        <h2>Publicação</h2>

        <form enctype="multuipart/form-data" methot= "post" asp-controller="Feed" asp-action="Index">
        <textarea name="Descricao" id="escrever texto" placeholder="Digite aqui na descricao do post" required></textarea>

        <footer>


          <div>
            <label for="campo-upload" id="texto-upload">Faça upload da sua imagem aqui....
            </label>
            <input type="file" name="image" id="campo-upload">

            <button type="submit" class="formulario-botao-azul">Postar</button>

        </form>

           </div>
        </footer>
      </section>
 

      <section id="publicacoes">

      @foreach (TbPublicacao publi in Model)
      {
      
      if(!publi.ImagemUrl.IsNullOrEmpty())
      { 
        <article class="card-publi">
          <header>

            <a href="#">
              <img class="foto-perfil" src="~/images/@publi.IdUsuarioNavigation?.FotoPerfilUrl">
              alt="Foto de Perfil"
              @publi.IdUsuarioNavigation?.NomeDeUsuario
            </a>
          </header>
          <figure>
            <img class="imagem-publicacao" src="~/images/@publi.ImagemUrl" alt="">

            <figcaption class="descricao-publicacao">
             @publi.IdUsuarioNavigation?.NomeDeUsuario
             <p>@publi.Descricao</p>
            </figcaption>

            <div class="interacoes-publicacao">
              <button>
                <img src="../images/icone-coracao-preto.svg" alt="">
              </button>

              <button>
                <img src="../images/icone-comentario-preto.svg" alt="">
              </button>

              <span>150k de curtidas</span>

            </div>


          </figure>

           <button type="button">Ver mais comentários...</button>

        </article>


      }
     
     
      }

      
      </section>




    </div>
  </main>